### ISSUE TITLE
for classification traing

### ISSUE THREAD

**Issue by AlexNmSED** [clemsgrs/hipt#11]
![1684829930620](https://github.com/clemsgrs/hipt/assets/42379333/e5539749-6917-4756-94f7-ce75779f70c2)

Hello,  When I was doing feature extraction, I encountered the above problem, do you have a solution? Are you facing the same problem.

**Comment by AlexNmSED** [comment]
I use the Pytorch 1.8

**Comment by clemsgrs** [comment]
hey, could you tell me which python version you're using?

**Comment by AlexNmSED** [comment]
Yes ， Python 3.8.16 . Should I be using a higher base python?

**Comment by clemsgrs** [comment]
try upgrading to python 3.9

**Comment by AlexNmSED** [comment]
In order to reduce other conflicts. Can you share the conda environment configuration file? This will reduce the hassle. Thank you for your help.











XinYu&nbsp;Hao,&nbsp;Master&nbsp;Student
JYU

---Original---
From: "clement ***@***.***&gt;
Date: Tue, May 23, 2023 11:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [clemsgrs/hipt] for distributed training (Issue #11)




 
try upgrading to python 3.9

**Comment by clemsgrs** [comment]
If you still run into some distributed-related issues, you can try upgrading to torch 1.12

**Comment by AlexNmSED** [comment]
Thank you.


I will do it.









XinYu&nbsp;Hao,&nbsp;Master&nbsp;Student
The&nbsp;Alpha&nbsp;Lab&nbsp;(http://thealphalab.org)
School&nbsp;of&nbsp;Software,&nbsp;Dalian&nbsp;University&nbsp;of&nbsp;Technology,&nbsp;Development&nbsp;Zone,&nbsp;Dalian&nbsp;116620,&nbsp;China
***@***.***

---Original---
From: "clement ***@***.***&gt;
Date: Tue, May 23, 2023 12:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [clemsgrs/hipt] for distributed training (Issue #11)




 
If you still run into some distributed-related issues, you can try upgrading to torch 1.12

**Comment by AlexNmSED** [comment]
Thank you for your help. The feature extraction is going fine.

**Comment by AlexNmSED** [comment]
I have solved this problem. The reason is: the task names in the source/components.py, source/models.py files conflict with each other in the configuration file.

Thank you again！

**Comment by AlexNmSED** [comment]
Hello , when I try  agg_method: 'self_att',  I encountered the following problems:

slide_pos_embed:
    use: False
    type: '1d'
AssertionError: was expecting embedding dimension of 192, but got 1

slide_pos_embed:
    use: True
    type: '1d'
AssertionError: query should be unbatched 2D or batched 3D tensor but received 4-D query tensor

slide_pos_embed:
    use: True
    type: '2d'
TypeError: forward() missing 1 required positional argument: 'coords'

How should I use self-attention, can you give me some advice? 
Thank you for your help.

**Comment by clemsgrs** [comment]
hi, `agg_method: 'self_att'` is not fully supported yet
my idea was to add a 4th level of self-attention on top of the slide-level Transformer to manage cases where the label is assigned to a group of slides (rather than a single slide), but i haven't had time to thoroughly test it.

I'd suggest using `agg_method: 'concat'`, which will simply concatenate regions extracted from multiple slides into a single -- longer -- sequence.
