### ISSUE TITLE
Exctract features has empty feature list

### ISSUE THREAD

**Issue by PierpaoloV** [clemsgrs/hipt#12]
Hi, when running python3 extract_features.py I run into the following error:
![Schermata 2023-09-13 alle 17 43 44](https://github.com/clemsgrs/hipt/assets/58755416/215e3e9c-b398-4c6f-9b2f-f8d74381228a)

I cannot understand what the problem is. 
I made sure that the files exist, the directories exist and also the patches are correctly specified.

**Comment by clemsgrs** [comment]
hi, it usually means that the `features_dir` in the confiugaration files points to the wrong directory.
